# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor1= torch.rand(size=(7,7))
tensor1

tensor([[0.2038, 0.9528, 0.0960, 0.7522, 0.9430, 0.5365, 0.5790],
        [0.8557, 0.3561, 0.2493, 0.6554, 0.3203, 0.3892, 0.8787],
        [0.9231, 0.5825, 0.7145, 0.8018, 0.3491, 0.8050, 0.3565],
        [0.6656, 0.3555, 0.2528, 0.7732, 0.0085, 0.8021, 0.3390],
        [0.8966, 0.5406, 0.6710, 0.7777, 0.7432, 0.7586, 0.8371],
        [0.5433, 0.3461, 0.2698, 0.8366, 0.0300, 0.9165, 0.1290],
        [0.9483, 0.2121, 0.3693, 0.6253, 0.2406, 0.1343, 0.0694]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
tensor2 = torch.rand(size=(1,7))
print('tensor2')
print(tensor2)
# Perform matrix multiplication
tensor3 =torch.transpose(tensor2, 0, 1)
print('tensor3')
print(tensor3)
torch.matmul(tensor1, tensor3)

tensor2
tensor([[0.7624, 0.9658, 0.8253, 0.1896, 0.1725, 0.0118, 0.1431]])
tensor3
tensor([[0.7624],
        [0.9658],
        [0.8253],
        [0.1896],
        [0.1725],
        [0.0118],
        [0.1431]])


tensor([[2.3767],
        [2.0214],
        [1.1333],
        [0.6179],
        [1.0600],
        [1.8364],
        [1.7989]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1= torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1,7))

# Matrix multiply tensors
torch.matmul(tensor1, torch.transpose(tensor2, 0, 1))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [25]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch. cuda. is_available()

# Create two random tensors on GPU
tensor_A= torch.rand(size=(2,3))
tensor_Agpu = tensor_A.to('cuda:0')
tensor_B= torch.rand(size=(2,3))
tensor_Bgpu = tensor_B.to('cuda:0')
print(tensor_Agpu)
print(tensor_Bgpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
tensor_AB = torch.matmul(tensor_Agpu, torch.transpose(tensor_Bgpu, 0, 1))
print(tensor_AB, tensor_AB.size())

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
max_value = torch.max(tensor_AB)
# Find min
min_value = torch.min(tensor_AB)

print(min_value, max_value)

tensor(0.3647, device='cuda:0') tensor(0.5617, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
max_pos = torch.argmax(tensor_AB)

# Find arg min
min_pos = torch.argmin(tensor_AB)

print(min_pos, max_pos)

tensor(0, device='cuda:0') tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [3]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_C = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_Cflat = tensor_C.flatten()

# Print out tensors and their shapes
print(tensor_C, tensor_C.size())
print(tensor_Cflat, tensor_Cflat.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
