# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
tensor1= torch.rand(size=(7,7))
tensor1

tensor([[0.7033, 0.6701, 0.9841, 0.8081, 0.8695, 0.9890, 0.4627],
        [0.1686, 0.9868, 0.7434, 0.7485, 0.8427, 0.0912, 0.2646],
        [0.4703, 0.0081, 0.5555, 0.5174, 0.7145, 0.0086, 0.6079],
        [0.3218, 0.0387, 0.3229, 0.0354, 0.0917, 0.1035, 0.3143],
        [0.3645, 0.5007, 0.0074, 0.9469, 0.4562, 0.4860, 0.1989],
        [0.5173, 0.4622, 0.7614, 0.5483, 0.8069, 0.7104, 0.8086],
        [0.1938, 0.8041, 0.6976, 0.8681, 0.3352, 0.4833, 0.4942]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
tensor2 = torch.rand(size=(1,7))
print('tensor2')
print(tensor2)
# Perform matrix multiplication
tensor3 =torch.transpose(tensor2, 0, 1)
print('tensor3')
print(tensor3)
torch.matmul(tensor1, tensor3)

tensor2
tensor([[0.7624, 0.9658, 0.8253, 0.1896, 0.1725, 0.0118, 0.1431]])
tensor3
tensor([[0.7624],
        [0.9658],
        [0.8253],
        [0.1896],
        [0.1725],
        [0.0118],
        [0.1431]])


tensor([[2.3767],
        [2.0214],
        [1.1333],
        [0.6179],
        [1.0600],
        [1.8364],
        [1.7989]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1= torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1,7))

# Matrix multiply tensors
torch.matmul(tensor1, torch.transpose(tensor2, 0, 1))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [25]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch. cuda. is_available()

# Create two random tensors on GPU
tensor_A= torch.rand(size=(2,3))
tensor_Agpu = tensor_A.to('cuda:0')
tensor_B= torch.rand(size=(2,3))
tensor_Bgpu = tensor_B.to('cuda:0')
print(tensor_Agpu)
print(tensor_Bgpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
tensor_AB = torch.matmul(tensor_Agpu, torch.transpose(tensor_Bgpu, 0, 1))
print(tensor_AB, tensor_AB.size())

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
